manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: zzeneg 
      url-base: https://github.com/zzeneg
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-nice-view-hid 
      remote: zzeneg
      revision: main
    - name: zmk-raw-hid 
      remote: zzeneg
      revision: main
  self:
    path: config
